#############################################################################
# Makefile for building: StyleCoin
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  StyleCoin.pro
# Template: app
# Command: C:/devel/qt5.5.0-static/bin/qmake.exe USE_UPNP=1 USE_IPV6=1 USE_QRCODE=1 -o Makefile StyleCoin.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:/devel/qt5.5.0-static/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: StyleCoin.pro C:/devel/qt5.5.0-static/mkspecs/win32-g++/qmake.conf C:/devel/qt5.5.0-static/mkspecs/features/spec_pre.prf \
		C:/devel/qt5.5.0-static/mkspecs/qdevice.pri \
		C:/devel/qt5.5.0-static/mkspecs/features/device_config.prf \
		C:/devel/qt5.5.0-static/mkspecs/qconfig.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_3dcore.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axbase.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axserver.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_clucene_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_concurrent.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_core.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_core_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_designer.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_designer_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_enginio.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_enginio_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_gui.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_gui_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_help.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_help_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_multimedia.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_network.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_network_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_nfc.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_platformsupport_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_positioning.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_printsupport.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_qml.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_qml_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_sensors.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_serialport.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_sql.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_sql_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_svg.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_svg_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_testlib.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_uitools.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_webchannel.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_websockets.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_widgets.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_winextras.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_xml.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_xml_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_dsengine.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qdds.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qicns.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qico.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qjp2.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qminimal.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qmng.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qsqlodbc.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qsvg.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qsvgicon.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtga.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtiff.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qwbmp.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qwebp.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qwindows.pri \
		C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		C:/devel/qt5.5.0-static/mkspecs/features/qt_functions.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/qt_config.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/win32/qt_config.prf \
		C:/devel/qt5.5.0-static/mkspecs/win32-g++/qmake.conf \
		C:/devel/qt5.5.0-static/mkspecs/features/spec_post.prf \
		.qmake.stash \
		C:/devel/qt5.5.0-static/mkspecs/features/exclusive_builds.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/default_pre.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/win32/default_pre.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/resolve_config.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/exclusive_builds_post.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/default_post.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/win32/rtti.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/precompile_header.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/warn_on.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/qt.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/resources.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/moc.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/uic.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/win32/windows.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/testcase_targets.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/exceptions.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/yacc.prf \
		C:/devel/qt5.5.0-static/mkspecs/features/lex.prf \
		StyleCoin.pro \
		C:/devel/qt5.5.0-static/lib/qtmain.prl \
		C:/devel/qt5.5.0-static/lib/Qt5PrintSupport.prl \
		C:/devel/qt5.5.0-static/lib/Qt5Widgets.prl \
		C:/devel/qt5.5.0-static/lib/Qt5Gui.prl \
		C:/devel/qt5.5.0-static/lib/Qt5Network.prl \
		C:/devel/qt5.5.0-static/lib/Qt5Core.prl \
		C:/devel/qt5.5.0-static/plugins/printsupport/windowsprintersupport.prl \
		C:/devel/qt5.5.0-static/plugins/platforms/qwindows.prl \
		C:/devel/qt5.5.0-static/plugins/imageformats/qdds.prl \
		C:/devel/qt5.5.0-static/plugins/imageformats/qicns.prl \
		C:/devel/qt5.5.0-static/plugins/imageformats/qico.prl \
		C:/devel/qt5.5.0-static/plugins/imageformats/qjp2.prl \
		C:/devel/qt5.5.0-static/plugins/imageformats/qmng.prl \
		C:/devel/qt5.5.0-static/plugins/imageformats/qtga.prl \
		C:/devel/qt5.5.0-static/plugins/imageformats/qtiff.prl \
		C:/devel/qt5.5.0-static/plugins/imageformats/qwbmp.prl \
		C:/devel/qt5.5.0-static/plugins/imageformats/qwebp.prl \
		C:/devel/qt5.5.0-static/plugins/bearer/qgenericbearer.prl \
		C:/devel/qt5.5.0-static/plugins/bearer/qnativewifibearer.prl
	$(QMAKE) USE_UPNP=1 USE_IPV6=1 USE_QRCODE=1 -o Makefile StyleCoin.pro
C:/devel/qt5.5.0-static/mkspecs/features/spec_pre.prf:
C:/devel/qt5.5.0-static/mkspecs/qdevice.pri:
C:/devel/qt5.5.0-static/mkspecs/features/device_config.prf:
C:/devel/qt5.5.0-static/mkspecs/qconfig.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_3dcore.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axbase.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axbase_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axcontainer.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axserver.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_axserver_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_bluetooth.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_clucene_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_concurrent.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_core.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_core_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_designer.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_designer_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_enginio.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_enginio_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_gui.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_gui_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_help.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_help_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_multimedia.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_network.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_network_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_nfc.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_nfc_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_platformsupport_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_positioning.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_positioning_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_printsupport.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_qml.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_qml_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_sensors.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_sensors_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_serialport.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_serialport_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_sql.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_sql_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_svg.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_svg_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_testlib.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_testlib_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_uiplugin.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_uitools.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_uitools_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_webchannel.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_websockets.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_websockets_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_widgets.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_widgets_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_winextras.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_winextras_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_xml.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_xml_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_xmlpatterns.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_dsengine.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qdds.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qgenericbearer.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qicns.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qico.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qjp2.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qminimal.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qmng.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qnativewifibearer.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qsqlodbc.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qsvg.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qsvgicon.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtaudio_windows.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtga.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtiff.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qwbmp.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qwebp.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_qwindows.pri:
C:/devel/qt5.5.0-static/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
C:/devel/qt5.5.0-static/mkspecs/features/qt_functions.prf:
C:/devel/qt5.5.0-static/mkspecs/features/qt_config.prf:
C:/devel/qt5.5.0-static/mkspecs/features/win32/qt_config.prf:
C:/devel/qt5.5.0-static/mkspecs/win32-g++/qmake.conf:
C:/devel/qt5.5.0-static/mkspecs/features/spec_post.prf:
.qmake.stash:
C:/devel/qt5.5.0-static/mkspecs/features/exclusive_builds.prf:
C:/devel/qt5.5.0-static/mkspecs/features/default_pre.prf:
C:/devel/qt5.5.0-static/mkspecs/features/win32/default_pre.prf:
C:/devel/qt5.5.0-static/mkspecs/features/resolve_config.prf:
C:/devel/qt5.5.0-static/mkspecs/features/exclusive_builds_post.prf:
C:/devel/qt5.5.0-static/mkspecs/features/default_post.prf:
C:/devel/qt5.5.0-static/mkspecs/features/win32/rtti.prf:
C:/devel/qt5.5.0-static/mkspecs/features/precompile_header.prf:
C:/devel/qt5.5.0-static/mkspecs/features/warn_on.prf:
C:/devel/qt5.5.0-static/mkspecs/features/qt.prf:
C:/devel/qt5.5.0-static/mkspecs/features/resources.prf:
C:/devel/qt5.5.0-static/mkspecs/features/moc.prf:
C:/devel/qt5.5.0-static/mkspecs/features/uic.prf:
C:/devel/qt5.5.0-static/mkspecs/features/win32/windows.prf:
C:/devel/qt5.5.0-static/mkspecs/features/testcase_targets.prf:
C:/devel/qt5.5.0-static/mkspecs/features/exceptions.prf:
C:/devel/qt5.5.0-static/mkspecs/features/yacc.prf:
C:/devel/qt5.5.0-static/mkspecs/features/lex.prf:
StyleCoin.pro:
C:/devel/qt5.5.0-static/lib/qtmain.prl:
C:/devel/qt5.5.0-static/lib/Qt5PrintSupport.prl:
C:/devel/qt5.5.0-static/lib/Qt5Widgets.prl:
C:/devel/qt5.5.0-static/lib/Qt5Gui.prl:
C:/devel/qt5.5.0-static/lib/Qt5Network.prl:
C:/devel/qt5.5.0-static/lib/Qt5Core.prl:
C:/devel/qt5.5.0-static/plugins/printsupport/windowsprintersupport.prl:
C:/devel/qt5.5.0-static/plugins/platforms/qwindows.prl:
C:/devel/qt5.5.0-static/plugins/imageformats/qdds.prl:
C:/devel/qt5.5.0-static/plugins/imageformats/qicns.prl:
C:/devel/qt5.5.0-static/plugins/imageformats/qico.prl:
C:/devel/qt5.5.0-static/plugins/imageformats/qjp2.prl:
C:/devel/qt5.5.0-static/plugins/imageformats/qmng.prl:
C:/devel/qt5.5.0-static/plugins/imageformats/qtga.prl:
C:/devel/qt5.5.0-static/plugins/imageformats/qtiff.prl:
C:/devel/qt5.5.0-static/plugins/imageformats/qwbmp.prl:
C:/devel/qt5.5.0-static/plugins/imageformats/qwebp.prl:
C:/devel/qt5.5.0-static/plugins/bearer/qgenericbearer.prl:
C:/devel/qt5.5.0-static/plugins/bearer/qnativewifibearer.prl:
qmake: FORCE
	@$(QMAKE) USE_UPNP=1 USE_IPV6=1 USE_QRCODE=1 -o Makefile StyleCoin.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
	-$(DEL_FILE) C:/Users/wolfgang/Documents/Privat/Coins/Dev/StyleCoin/stylecoin/src/leveldb/libleveldb.a;
	-$(DEL_FILE) cd
	-$(DEL_FILE) C:/Users/wolfgang/Documents/Privat/Coins/Dev/StyleCoin/stylecoin/src/leveldb
	-$(DEL_FILE) ;
	-$(DEL_FILE) clean
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:/Users/wolfgang/Documents/Privat/Coins/Dev/StyleCoin/stylecoin/stylecoin_plugin_import.cpp .qmake.stash

C:/Users/wolfgang/Documents/Privat/Coins/Dev/StyleCoin/stylecoin/src/leveldb/libleveldb.a: FORCE

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
